### ISSUE TITLE
getting a syntax error on the first run of npm run server

### ISSUE THREAD

**Issue by munirkizilcali** [socialtables/venue-app-challenge#3]
I just cloned the repo,
npm install & npm run server. Getting an error on server/graphql/types/review.js:55 on the spread operator. You can find the error code below:

`// ♥ git clone git@github.com:socialtables/venue-app-challenge.git
Cloning into 'venue-app-challenge'...
remote: Counting objects: 74, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 74 (delta 10), reused 64 (delta 4), pack-reused 0
Receiving objects: 100% (74/74), 33.72 MiB | 10.66 MiB/s, done.
Resolving deltas: 100% (10/10), done.
[11:32:03] code
// ♥ cd venue-app-challenge/
[11:32:06] (master) venue-app-challenge
// ♥ npm install

> fsevents@1.2.4 install /Users/munirkizilcali/Development/code/venue-app-challenge/node_modules/fsevents
> node install

[fsevents] Success: "/Users/munirkizilcali/Development/code/venue-app-challenge/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/munirkizilcali/Development/code/venue-app-challenge/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> nodemon@1.18.3 postinstall /Users/munirkizilcali/Development/code/venue-app-challenge/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN venue-app-challenge@1.0.0 No repository field.
npm WARN venue-app-challenge@1.0.0 No license field.

added 1567 packages from 869 contributors and audited 16160 packages in 40.093s
found 0 vulnerabilities

[11:32:51] (master) venue-app-challenge
// ♥ npm run server

> venue-app-challenge@1.0.0 server /Users/munirkizilcali/Development/code/venue-app-challenge
> nodemon --watch server --exec node ./server/index.js

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/munirkizilcali/Development/code/venue-app-challenge/server/**/*
[nodemon] starting `node ./server/index.js`
/Users/munirkizilcali/Development/code/venue-app-challenge/server/graphql/types/review.js:55
			...args
			^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/munirkizilcali/Development/code/venue-app-challenge/server/graphql/schema.js:8:16)
[nodemon] app crashed - waiting for file changes before starting...
  `

**Comment by munirkizilcali** [comment]
updated node version. Working fine now.
